# SonarQube / SonarCloud project configuration
sonar.projectKey=loerei_gemini-qol
sonar.organization=loerei
sonar.sources=src
sonar.exclusions=content.js,node_modules/**,dist/**
sonar.cpd.exclusions=content.js,node_modules/**,dist/**
